# Generated by Django 3.2.25 on 2025-01-07 09:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20250107_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneyin',
            name='money_processor',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moneyout',
            name='money_user',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
    ]
