# Generated by Django 3.2.25 on 2025-08-18 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_asset_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='category',
            field=models.CharField(choices=[('Tables', 'Tables'), ('Chairs', 'Chairs'), ('Computers', 'Computers'), ('Motocycles', 'Motocycles'), ('Beehives', 'Beehives'), ('Packages (kg)', 'Packages (kg)'), ('Labels', 'Labels'), ('Buckets', 'Buckets'), ('Bee suit', 'Bee suit'), ('Gloves', 'Gloves'), ('Hire tools', 'Hire tools'), ('Bee smoker', 'Bee smoker'), ('Honey press', 'Honey press'), ('Honey strainer', 'Honey strainer'), ('Sandles', 'Sandles'), ('Apron', 'Apron'), ('Cars', 'Cars')], default='other', max_length=50),
        ),
    ]
