# Generated by Django 3.2.25 on 2025-01-07 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20250107_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='masteramount',
            name='unique_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
