# Generated by Django 3.2.25 on 2025-01-07 15:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_masteramount_unique_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbuy',
            name='status',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
