# Generated by Django 3.2.25 on 2025-08-19 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_purchase_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='barcode_data',
            field=models.CharField(blank=True, help_text='Automatically filled by scanning a barcode', max_length=255, null=True),
        ),
    ]
