# Generated by Django 3.2.25 on 2025-01-08 05:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_productbuy_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneyrequest',
            name='status',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
    ]
