# Generated by Django 3.2.25 on 2025-08-20 08:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_purchaseitem_barcode_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmer',
            old_name='farmer_background',
            new_name='familia_mtazamo',
        ),
        migrations.AddField(
            model_name='farmer',
            name='kiasi_mwisho',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmer',
            name='kufanikisha_nin',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmer',
            name='kusaidia_mazingira',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmer',
            name='malengo',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmer',
            name='muhamasishaji',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmer',
            name='mwanzo',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='barcode_data',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
