# Generated by Django 3.2.25 on 2025-08-27 05:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20250820_1114'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, help_text='Generated e.g. CUST-0001', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Jina kamili la mteja au kampuni', max_length=200)),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=150, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Weka namba sahihi (tarakimu, +, -, mabano).', regex='^[0-9+\\-\\s()]{6,20}$')])),
                ('alt_phone', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Weka namba sahihi (tarakimu, +, -, mabano).', regex='^[0-9+\\-\\s()]{6,20}$')])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('alt_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address_line1', models.CharField(blank=True, max_length=250, null=True)),
                ('address_line2', models.CharField(blank=True, max_length=250, null=True)),
                ('city', models.CharField(blank=True, max_length=120, null=True)),
                ('region', models.CharField(blank=True, max_length=120, null=True)),
                ('country', models.CharField(blank=True, default='Tanzania', max_length=120, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('tin', models.CharField(blank=True, max_length=50, null=True, verbose_name='TIN')),
                ('vat_number', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_terms', models.CharField(choices=[('cash', 'Cash'), ('7d', 'Net 7 Days'), ('14d', 'Net 14 Days'), ('30d', 'Net 30 Days'), ('45d', 'Net 45 Days'), ('60d', 'Net 60 Days')], default='cash', max_length=10)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='asset',
            name='category',
            field=models.CharField(choices=[('Tables', 'Tables'), ('Chairs', 'Chairs'), ('Computers', 'Computers'), ('Motocycles', 'Motocycles'), ('Beehives', 'Beehives'), ('Packages (kg)', 'Packages (kg)'), ('Labels', 'Labels'), ('Buckets', 'Buckets'), ('Bee suit', 'Bee suit'), ('Gloves', 'Gloves'), ('Hire tools', 'Hire tools'), ('Bee smoker', 'Bee smoker'), ('Honey press', 'Honey press'), ('Honey strainer', 'Honey strainer'), ('Sandles', 'Sandles'), ('Apron', 'Apron'), ('Cars', 'Cars'), ('Filling Machine', 'Filling Machine'), ('Heating Tank', 'Heating Tank'), ('Printers', 'Printers'), ('Filter Pump', 'Filter Pump'), ('Storage Tank', 'Storage Tank'), ('Honey Pressor', 'Honey Pressor'), ('Cartering Machine', 'Cartering Machine'), ('Digital Refractometor', 'Digital Refractometor'), ('Analogy Refractometor', 'Analogy Refractometor')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='masteramount',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=1000),
        ),
    ]
