# Generated by Django 3.2.25 on 2025-01-08 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_salary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salary',
            old_name='time',
            new_name='paymentperiod',
        ),
    ]
