# Generated by Django 3.2.25 on 2025-01-15 09:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_rename_time_salary_paymentperiod'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneyrequest',
            name='completecheck',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
    ]
