# Generated by Django 3.2.25 on 2025-08-27 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20250827_0825'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='product',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='product',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='product',
            name='honey',
        ),
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
        migrations.RemoveField(
            model_name='product',
            name='used_rawmaterial',
        ),
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
        migrations.RemoveField(
            model_name='product',
            name='wax',
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(choices=[('Bee hives', 'Bee hives'), ('Round bee suit', 'Round bee suit'), ('Bee suit', 'Bee suit'), ('Bee smoker', 'Bee smoker'), ('Bee brush', 'Bee brush'), ('Hive tool', 'Hive tool'), ('Straw hat', 'Straw hat'), ('Queen excluder', 'Queen excluder'), ('Honey gate', 'Honey gate'), ('Entrance gate', 'Entrance gate'), ('Bee spacer', 'Bee spacer'), ('1 kg stinging honey', '1 kg stinging honey'), ('1/2 kg stinging honey', '1/2 kg stinging honey'), ('100 g stinging honey', '100 g stinging honey'), ('7 kg stinging honey', '7 kg stinging honey'), ('1 litre stingless honey', '1 litre stingless honey'), ('500 ml stingless honey', '500 ml stingless honey'), ('250 ml stingless honey', '250 ml stingless honey'), ('1 kg wax', '1 kg wax')], default=django.utils.timezone.now, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0, help_text='Current available stock'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('pcs', 'Pieces'), ('kg', 'Kilogram'), ('g', 'Gram'), ('ltr', 'Litre'), ('ml', 'Millilitre')], default='pcs', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price per unit', max_digits=12),
        ),
        migrations.CreateModel(
            name='ProductAdditionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('correct', 'Correct'), ('incorrect', 'Incorrect')], default='pending', max_length=10)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='web.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
