# Generated by Django 3.2.25 on 2025-01-16 10:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_moneyrequest_completecheck'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code_name', models.CharField(max_length=255)),
                ('uses', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default='inactive', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
