# Generated by Django 3.2.25 on 2025-09-03 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_salesorder_salesorderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('note', models.TextField(blank=True, null=True)),
                ('applied', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MaterialRequisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('note', models.TextField(blank=True, null=True)),
                ('applied', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='material',
            name='comb_honey',
        ),
        migrations.RemoveField(
            model_name='material',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='material',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='material',
            name='honey',
        ),
        migrations.RemoveField(
            model_name='material',
            name='status',
        ),
        migrations.RemoveField(
            model_name='material',
            name='user',
        ),
        migrations.RemoveField(
            model_name='material',
            name='wax',
        ),
        migrations.AddField(
            model_name='material',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='material',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='material',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=80, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='material',
            name='stock',
            field=models.PositiveIntegerField(default=0, help_text='Current stock in pieces'),
        ),
        migrations.AddField(
            model_name='material',
            name='unit',
            field=models.CharField(choices=[('pcs', 'Pieces')], default='pcs', max_length=10),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['name'], name='web_materia_name_0290f2_idx'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['is_active'], name='web_materia_is_acti_9a4a03_idx'),
        ),
        migrations.AddField(
            model_name='materialrequisition',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materialrequisition_decisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='materialrequisition',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materialrequisitions', to='web.material'),
        ),
        migrations.AddField(
            model_name='materialrequisition',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materialrequisition_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='materialreceipt',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materialreceipt_decisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='materialreceipt',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materialreceipts', to='web.material'),
        ),
        migrations.AddField(
            model_name='materialreceipt',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materialreceipt_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
