# Generated by Django 3.2.25 on 2025-01-16 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_qrcode_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='qr_pdfs/'),
        ),
    ]
