# Generated by Django 3.2.25 on 2025-09-04 09:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_auto_20250903_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseitem',
            name='barcode_data',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
