# Generated by Django 3.2.25 on 2025-01-23 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_qrcode_pdf_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tables', models.PositiveIntegerField()),
                ('Chairs', models.PositiveIntegerField()),
                ('Computers', models.PositiveIntegerField()),
                ('Motocycles', models.PositiveIntegerField()),
                ('Beehives', models.PositiveIntegerField()),
                ('Packages', models.PositiveIntegerField()),
                ('Labels', models.PositiveIntegerField()),
                ('Buckets', models.PositiveIntegerField()),
                ('Bee_suit', models.PositiveIntegerField()),
                ('Gloves', models.PositiveIntegerField()),
                ('Hire_tools', models.PositiveIntegerField()),
                ('Bee_smoker', models.PositiveIntegerField()),
                ('Honey_press', models.PositiveIntegerField()),
                ('Honey_strainer', models.PositiveIntegerField()),
                ('Sandles', models.PositiveIntegerField()),
                ('Apron', models.PositiveIntegerField()),
            ],
        ),
    ]
