# Generated by Django 3.2.25 on 2025-01-23 07:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_allasset'),
    ]

    operations = [
        migrations.AddField(
            model_name='allasset',
            name='unique_code',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
