# Generated by Django 3.2.25 on 2025-01-30 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_product_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_name',
        ),
    ]
