# Generated by Django 3.2.25 on 2025-02-03 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_masterproduct_productin_productout'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='profile_picture',
            field=models.FileField(blank=True, help_text='Optional', null=True, upload_to='home/'),
        ),
    ]
